#Message to be displayed on flyday when you join

#Here's a thingey for you to copy §

#   §0	Black, §1 Dark Blue, §2 Dark Green,, §4 Dark Red, §5 Dark Purple, §6 Gold, §7 Gray, 
#   §8 Dark Gray, §9 Blue, §a Green, §b Aqua, §c Red, §d Light Purple, §e Yellow, §f White
message: '§2Its flyday! Enjoy free flying all day!'